-- Beispielinhalte (Platzhalter!) – im SQL-Editor von Supabase ausführen

insert into public.site_settings (id, site_name, tagline, hero_title, hero_text, hero_image_url, about_title, about_intro, about_text, about_image_url, owner_name, street, zip, city, phone, email, instagram_handle, sales_info, announcement) values
  (1, 'Imkerei ausm Ländle', 'Echter Honig aus der Heimat', 'Honig mit Herkunft – direkt vom Imker aus dem Ländle', 'Unsere Bienen sammeln zwischen Streuobstwiesen, Waldrändern und blühenden Feldern. Wir schleudern schonend, füllen von Hand ab und verkaufen direkt – ohne Umwege.', null, 'Aus Liebe zur Biene', 'Was als Hobby mit zwei Völkern begann, ist heute eine kleine Imkerei mit Herz – nachhaltig, regional und mit viel Respekt vor der Natur.', '<p>Unsere Völker stehen an verschiedenen Plätzen rund um unseren Heimatort: an Streuobstwiesen, am Waldrand und zwischen Rapsfeldern. So entstehen je nach Jahreszeit ganz unterschiedliche Honige.</p><h2>Unsere Philosophie</h2><ul><li>Artgerechte Haltung und ruhiger Umgang mit den Bienen</li><li>Schonende Kaltschleuderung, kein Erhitzen über Stocktemperatur</li><li>Kurze Wege: vom Bienenstock direkt ins Glas</li></ul><p>Wir freuen uns über jeden Besuch – schreibt uns einfach vorher kurz an.</p>', null, 'Max Mustermann', 'Musterstraße 1', '70000', 'Musterstadt', '+49 123 456789', 'info@imkerei-ausm-laendle.de', 'imkerei_ausm_laendle_', 'Hofverkauf nach Absprache
Samstags 9–12 Uhr am Wochenmarkt', 'Der neue Sommerhonig ist da! 🍯')
on conflict (id) do update set site_name = excluded.site_name, tagline = excluded.tagline, hero_title = excluded.hero_title, hero_text = excluded.hero_text, hero_image_url = excluded.hero_image_url, about_title = excluded.about_title, about_intro = excluded.about_intro, about_text = excluded.about_text, about_image_url = excluded.about_image_url, owner_name = excluded.owner_name, street = excluded.street, zip = excluded.zip, city = excluded.city, phone = excluded.phone, email = excluded.email, instagram_handle = excluded.instagram_handle, sales_info = excluded.sales_info, announcement = excluded.announcement;

insert into public.products (name, slug, category, short_description, description, taste, consistency, harvest, size, price, image_url, available, featured, published, sort) values
  ('Frühjahrsblütenhonig', 'fruehjahrsbluetenhonig', 'honig', 'Mild, cremig gerührt – aus Obstblüte, Löwenzahn und Raps.', '<p>Unser erster Honig im Jahr. Die Bienen sammeln ihn in der Obstblüte, im Löwenzahn und im Raps. Durch sorgfältiges Rühren wird er wunderbar cremig und streichzart.</p>', 'Mild, blumig', 'Cremig', 'Mai', '500 g', 7.5, null, true, true, true, 1),
  ('Sommertracht', 'sommertracht', 'honig', 'Kräftig-aromatisch mit Linde und Wiesenblumen.', '<p>Im Sommer blühen Linde, Klee und viele Wiesenblumen. Das Ergebnis ist ein aromatischer, flüssiger Honig mit feiner Frische.</p>', 'Aromatisch, fruchtig', 'Flüssig', 'Juli', '500 g', 8, null, true, true, true, 2),
  ('Waldhonig', 'waldhonig', 'honig', 'Dunkel, würzig und malzig – nicht jedes Jahr verfügbar.', '<p>Waldhonig entsteht aus Honigtau von Tannen und Fichten. Er ist dunkel, würzig und wenig süß – ein echter Genuss für Kenner.</p>', 'Würzig, malzig', 'Flüssig', 'August', '500 g', 9.5, null, false, true, true, 3),
  ('Kleines Probierset', 'probierset', 'geschenk', 'Drei Sorten à 250 g – perfekt zum Verschenken.', '<p>Drei unserer Honige im kleinen Glas, schön verpackt. Ideal als Mitbringsel.</p>', null, null, null, '3 × 250 g', 14, null, true, false, true, 4),
  ('Bienenwachskerze', 'bienenwachskerze', 'wachs', 'Handgegossen aus eigenem Wachs, duftet dezent nach Honig.', '<p>Aus reinem Bienenwachs unserer Völker gegossen. Brennt ruhig und lange.</p>', null, null, null, 'ca. 10 cm', 6, null, true, false, true, 5);

insert into public.posts (title, slug, excerpt, content, image_url, published, published_at) values
  ('Die Sommerernte ist im Glas', 'sommerernte-im-glas', 'Nach einem warmen Juli konnten wir endlich schleudern – und die Ausbeute kann sich sehen lassen.', '<p>Nach einem warmen Juli konnten wir endlich schleudern. Die Linde hat dieses Jahr besonders gut gehonigt, entsprechend aromatisch ist die Sommertracht geworden.</p><p>Ab sofort gibt es den neuen Honig bei uns am Hof und auf dem Wochenmarkt.</p>', null, true, '2026-09-19'),
  ('Warum schwärmen Bienen?', 'warum-schwaermen-bienen', 'Im Frühjahr teilt sich ein Volk – ein faszinierendes Naturschauspiel. Wir erklären, was dahintersteckt.', '<p>Schwärmen ist die natürliche Vermehrung eines Bienenvolkes. Die alte Königin verlässt mit etwa der Hälfte der Bienen den Stock und sucht sich ein neues Zuhause.</p><p>Wenn ihr einen Schwarm seht: Ruhe bewahren und gerne bei uns melden!</p>', null, true, '2026-08-15'),
  ('Einwinterung: So kommen die Bienen durch die kalte Zeit', 'einwinterung', 'Futter, Varroa-Behandlung und Ruhe – so bereiten wir unsere Völker auf den Winter vor.', '<p>Im Spätsommer beginnt für uns Imker die Vorbereitung auf den Winter. Die Völker bekommen Futter, werden gegen die Varroamilbe behandelt und dann in Ruhe gelassen.</p>', null, true, '2026-06-26');

insert into public.events (title, date, time_from, time_to, location, description, published) values
  ('Wochenmarkt', '2026-09-26', '08:00', '12:00', 'Marktplatz Musterstadt', 'Frischer Honig und Kerzen an unserem Stand.', true),
  ('Tag der offenen Imkerei', '2026-10-10', '14:00', '17:00', 'Am Bienenhaus', 'Blick in den Bienenstock (mit Schutzausrüstung), Honigverkostung und Kaffee.', true),
  ('Weihnachtsmarkt', '2026-12-03', '11:00', '19:00', 'Rathausplatz', 'Honig, Geschenksets und Bienenwachskerzen.', true);

